Hw 1
mletunenko/epam_homework pull request #1
Opened 2021-09-05 16:51 UTC by mletunenko

Complete first homework

2021-09-05 20:18 UTC, PeppaTheC requested changes

2021-09-05 20:18 UTC, PeppaTheC commented on homework1/task02.py
> +    # Grow fib sec till meet first value of "data"
почему просто напряму не проверить равны ли первые два числа в массиве [0, 1]

2021-09-05 20:18 UTC, PeppaTheC commented on homework1/task02.py
> +    # Grow fib sec till meet first value of "data"
через например data[0:2] == [0,1]

2021-09-05 20:18 UTC, PeppaTheC commented on homework1/task02.py
> +        if first_zero_check:
зачем это каждый раз в цикле проверять, first zero не меняется от цикла к циклу

2021-09-05 20:18 UTC, PeppaTheC commented on homework1/task02.py
> +            gen.append(gen[-2] + gen[-1])
очень странно, зачем тут вообще массив? нужно ли знать только последнее и предыдущие число.

2021-09-05 20:18 UTC, PeppaTheC commented on homework1/task02.py
> +        while gen[-1] < data[0]:
что за странный цикл? он тут нужен?

2021-09-05 20:18 UTC, PeppaTheC commented on homework1/task03.py
> +        i = fi.readline()
что за название переменной?

2021-09-05 20:18 UTC, PeppaTheC commented on homework1/task03.py
> +        max_int = min_int = int(i)
max int  - что-то же станное

2021-09-05 20:18 UTC, PeppaTheC commented on homework1/task02.py
> +    gen = [0, 1]
gen -? что за название переменной, что оно означает?

2021-09-05 20:18 UTC, PeppaTheC commented on homework1/task02.py
> +    for v in data:
v -? лучше написать полностью value

2021-09-05 20:18 UTC, PeppaTheC commented on homework1/task03.py
> +            v = int(line)
опять v - ничего не значащие, очень затрудняет чтение

2021-09-05 20:18 UTC, PeppaTheC commented on homework1/task04.py
> +    for av in a:
какая временная сложность у данного алгоритма?

2021-09-05 20:18 UTC, PeppaTheC commented on homework1/task05.py
> +        return 0
максимальная сумма в subarray может равняться нулю. 
Нужно использовать другое значение

2021-09-05 20:18 UTC, PeppaTheC commented on homework1/task05.py
> +            w = nums[i:i + w_size]
w?

2021-09-05 20:18 UTC, PeppaTheC commented on tests/homework1/test_task02.py
> +    assert check_fibonacci([89, 144, 233])
это не последовательность фибоначчи - почему true?

2021-09-05 20:18 UTC, PeppaTheC commented on tests/homework1/test_task03.py
> +    fd, path = tempfile.mkstemp(suffix='.txt', text=True)
```Unlike TemporaryFile(), the user of mkstemp() is responsible for deleting the temporary file when done with it.```

2021-09-05 20:18 UTC, PeppaTheC commented on tests/homework1/test_task03.py
> +import tempfile
тестов малова-то, где тест с пустым файлом, файлом с одним числом и т.п

2021-09-06 18:26 UTC, PeppaTheC commented on homework1/task02.py
> +    # Grow fib sec till meet first value of "data"
да

2021-09-07 18:13 UTC, mletunenko commented on homework1/task02.py
> +    # Grow fib sec till meet first value of "data"
спасибо, решение переписала с учетом того, что передаваемая последовательность которую мы проверяем всегда начинается с [0, 1]

2021-09-09 08:55 UTC, PeppaTheC approved these changes

2021-09-09 08:55 UTC, PeppaTheC commented on homework1/task03.py
> +            return None
None не соответствует возвращаемой аннотации.
Tuple[int, int]

2021-09-09 08:55 UTC, PeppaTheC commented on homework1/task05.py
> +        return None
тоже не соответствует аннотации  `-> int`

2021-09-12 12:40 UTC, merged