Hw12
mletunenko/epam_homework pull request #12
Opened 2021-10-25 18:53 UTC by mletunenko

2021-10-31 18:55 UTC, PeppaTheC requested changes

2021-10-31 18:55 UTC, PeppaTheC commented on homework12/task/mysite/settings.py
> +SECRET_KEY = 'django-insecure-=bv09gdqcg*t1_1$w&r5+' \
это можно стоит постить на git?

2021-10-31 18:55 UTC, PeppaTheC commented on homework12/task/study/models.py
> +    text = models.CharField(max_length=100, db_index=True)
есть объяснение зачем тут индекс?

2021-11-02 10:31 UTC, mletunenko commented on homework12/task/study/models.py
> +    text = models.CharField(max_length=100, db_index=True)
согласно заданию - нужно добавить индексы. Это поле выбрала поскольку, предполагаю,: что поиск будет производится именно по нему

2021-11-02 10:50 UTC, mletunenko commented on homework12/task/mysite/settings.py
> +SECRET_KEY = 'django-insecure-=bv09gdqcg*t1_1$w&r5+' \
нельзя, спрятала. Спасибо!

2021-11-03 15:23 UTC, PeppaTheC approved these changes

2021-11-10 19:17 UTC, merged