Hw 2
mletunenko/epam_homework pull request #2
Opened 2021-09-09 07:39 UTC by mletunenko

Second homework

2021-09-12 18:17 UTC, PeppaTheC requested changes

2021-09-12 18:17 UTC, PeppaTheC commented on homework2/task01.py
> +        most_common_char = None
return None не совпадает с аннотацией возвращаемого типа

2021-09-12 18:17 UTC, PeppaTheC commented on homework2/task01.py
> +        while True:
почему просто не `for line in file`?

2021-09-15 15:22 UTC, mletunenko commented on homework2/task03.py
> +    return [list(i) for i in itertools.product(*args)]
принято

2021-09-16 08:49 UTC, PeppaTheC commented on homework2/task01.py
> +    # Create a storage list which contains a tuple (len of word, word)
https://towardsdatascience.com/why-good-codes-dont-need-comments-92f58de19ad2

2021-09-16 10:41 UTC, mletunenko commented on homework2/task01.py
> +    # Create a storage list which contains a tuple (len of word, word)
информация интересная и полезная, спасибо) комменты удалила

2021-09-19 20:48 UTC, PeppaTheC approved these changes

2021-09-21 06:35 UTC, merged