third homework first version
mletunenko/epam_homework pull request #3
Opened 2021-09-12 17:01 UTC by mletunenko

HM #3

2021-09-12 18:21 UTC, PeppaTheC requested changes

2021-09-12 18:21 UTC, PeppaTheC commented on homework3/task02.py
> +    with Pool(501) as p:
что за магическое число 501? 501 процесс это много?

2021-09-12 18:21 UTC, PeppaTheC commented on homework3/task03.py
> +        def keyword_filter_func(data):
судя по замыканию key, value всегда будут последними значениями из keywords. Что будет если задать несколько полей

2021-09-12 18:21 UTC, PeppaTheC commented on homework3/task03.py
> +    def __init__(self, functions):
я бы добавил аннотацию типо

2021-09-15 16:48 UTC, mletunenko commented on homework3/task03.py
> +        def keyword_filter_func(data):
будут одинаковые функции с послденими значениями key, value. Спасибо! исправлено

2021-09-15 17:04 UTC, mletunenko commented on homework3/task03.py
> +    def __init__(self, functions):
теперь есть

2021-09-16 08:51 UTC, PeppaTheC approved these changes

2021-09-16 08:51 UTC, PeppaTheC commented on homework3/task03.py
> +    def __init__(self, functions):
изменение не дошло)

2021-09-19 20:52 UTC, PeppaTheC approved these changes

2021-09-19 20:52 UTC, PeppaTheC commented on homework3/task03.py
> +# positive_even = Filter(lamba a: a % 2 == 0, lambda a: a > 0,
тут конечно в примере не лист)

2021-09-21 06:34 UTC, merged